services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus3
    expose:
      - 8081
      - 8082
      - 8083
    volumes:
      - nexus-data:/nexus-data
    environment:
      - NEXUS_CONTEXT=
    networks:
      - nginx-network
    restart: unless-stopped

volumes:
  nexus-data:
    driver: local

networks:
  nginx-network:
    external: true
