services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_config:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['initial_root_password'] = 'JZcddWInT0UKusJ'
        # Add additional GitLab configuration here if needed
    networks:
      - nginx-network

volumes:
  gitlab_data:
  gitlab_logs:
  gitlab_config:

networks:
  nginx-network:
    external: true