services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access Docker daemon
      - portainer_data:/data # Persistent storage for Portainer data
    networks:
      - nginx-network
volumes:
  portainer_data:

networks:
  nginx-network:
    external: true