services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "33307:3306"  # Exposes port 3306 inside the container to port 13307 on the host
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
